routes/web.php
<?php

use App\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//blog route
Route::get('/posts', 'Frontend\MainController@posts')->name('frontend.posts');
Route::get('/posts/{slug}', 'Frontend\PostController@show')->name('frontend.posts.show');
Route::post('comments/{postId}', 'Frontend\CommentController@store')->name('frontend.comments.store');
Route::post('comments}', 'Frontend\CommentController@reply')->name('frontend.comments.reply');
Route::get('search', 'Frontend\PostController@searchTitle' )->name('frontend.posts.search');



// personal-site route

Route::get('/', function () {
    $recently = Post::with('user', 'category', 'photo')
        ->where('status', 1)
        ->orderBy('created_at', 'desc')->paginate(3);
    return view('welcome', compact('recently'));
})->name('home');
Route::get('/about_me', 'Frontend\MainController@about_me')->name('about_me');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('contact','Frontend\MailController');


// admin route
Route::group(['before' => 'auth', 'middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('dashboard', 'Admin\AdminDashboardController@index')->name('dashboard');
    Route::resource('users', 'Admin\AdminUserController');
    Route::resource('posts', 'Admin\AdminPostController');
    Route::resource('categories', 'Admin\AdminCategoryController');
    Route::resource('photos', 'Admin\AdminPhotoController');
    Route::get('photos/upload', ['as' => 'photos.upload', 'use' => 'Admin\AdminPhotoController@upload']);
    Route::get('comments', 'Admin\CommentController@index')->name('comments.index');
    Route::post('actions/{id}', 'Admin\CommentController@actions')->name('comments.actions');
    Route::get('comments/{id}', 'Admin\CommentController@edit')->name('comments.edit');
    Route::patch('comments/{id}', 'Admin\CommentController@update')->name('comments.update');
    Route::delete('comments/{id}', 'Admin\CommentController@destroy')->name('comments.destroy');
    Route::delete('delete/media', 'Admin\AdminPhotoController@deleteAll')->name('photo.delete.all');
});
Route::get('locale/{locale}', function ($locale) {
  \Illuminate\Support\Facades\Session::put('locale',$locale);
  return redirect()->back();
});

resources/views/partials/about_me.blade.php
@extends('layouts.master')
@section('about_me')
    <body>

    <!--================ Start Header Area =================-->

    <!--================ End Header Area =================-->

    <!--================ Start Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
                <div class="banner_content text-center">
                    <h2>{{__('msg.profile')}}</h2>
                    <div class="page_link">
                        <a href="{{route('home')}}">{{__('msg.home')}}</a>
                        <a href="{{route('about_me')}}">{{__('msg.profile')}}</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Banner Area =================-->

    <!--================Start Portfolio Details Area =================-->
    <section class="portfolio_details_area section-margin">
        <div class="container">
            <div class="row">
                <div class="offset-xl-1 col-xl-10">
                    <div class="portfolio_details_inner">
                        <div class="row">
                            <div class="col-12">
                                <div class="left_img">
                                    <img class="img-fluid" src="img/portfolio/portfolio-details.png" alt="">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-7 mb-4 mb-lg-0">
                                <p>{{__('msg.content1')}} </p>
                                <h3  >php& laravel framework ,vue ,sql server ,mysql  </h3>
                                <p>
                                    {{__('msg.content2')}}
                                </p>
                                <p>   {{__('msg.content3')}}</p>
                                <p>{{__('msg.content4')}}  </p>
                            </div>
                            <div class="col-lg-5">
                                <div class="portfolio_right_text mt-30">
                                    <h4 class="text-uppercase">{{__('msg.my_details')}}</h4>

                                    <ul class="list">
                                        <li><span>{{__('msg.name')}}</span>{{__('msg.side1')}}</li>
                                        <li><span>{{__('msg.education')}}</span>{{__('msg.side2')}}</li>
                                        <li><span>{{__('msg.full_stack')}}</span>{{__('msg.side3')}}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Portfolio Details Area =================-->

    <!--================ Start Brands Area =================-->
    <section class="brands-area section_gap_bottom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                </div>
            </div>
        </div>
    </section>
    <!--================ End Brands Area =================-->


    <!--================Footer Area =================-->

    <!--================End Footer Area =================-->



    </body>
    @endsection

resources/views/partials/comments.blade.php
<script type="text/javascript">
    $(".btn-open").on("click",function(){
        $('.form-reply').css('display', 'none');
        var service = this.id;
        var service_id = '#f-' + service;
        $(service_id).show('slow');
    });
</script>
@foreach($comments as $comment)
    <div class="comments-area">

        <div class="comment-list">
            <div class="single-comment justify-content-between d-flex">
                <div class="user justify-content-between d-flex">

                    <div class="desc">
                        <p class="comment">
                            {{$comment->description}}
                        </p>

                        <div class="d-flex justify-content-between">
                            <div class="d-flex align-items-center">
                                <h5>-
                                    <a href="#">{{$comment->name}}</a>
                                </h5>
                                <p class="date">{{\Hekmatinasser\Verta\Verta::instance($comment->created_at)->formatDatetime()}} </p>
                            </div>

                            <div class="reply-btn">
                                <button class="btn btn-dribbble btn-open" id="div-comment-{{$comment->id}}">پاسخ
                                </button>
                            </div>
                            <div class="form-reply col-md-12" id="f-div-comment-{{$comment->id}}" style="display: none">
                                {!! Form::open(['method' => 'POST', 'route'=> ['frontend.comments.reply']]) !!}
                                @csrf
                                <div class="form-group">
                                    {!! Form::hidden('parent_id', $comment->id) !!}
                                    {!! Form::hidden('post_id', $post->id) !!}

                                    <div class="form-group">
                                        <textarea class="form-control w-100" name="description" id="comment" cols="30" rows="9" placeholder="نظر خود را بنویسید"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="primary_btn button-contactForm">ثبت پاسخ</button>
                                </div>
                                {!! Form::close() !!}
                            </div>
                            @include('partials.comments', ['comments' => $comment->replies])
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
@endforeach

resources/views/partials/contact.blade.php
@extends('layouts.master')
@section('about_me')
<body>

<!--================ Start Header Area =================-->
<!--================ End Header Area =================-->

<!--================ Start Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>{{__('msg.contact')}}</h2>
                <div class="page_link">
                    <a href="{{route('home')}}">{{__('msg.home')}}</a>
                    <a href="{{route('contact.index',app()->getLocale())}}">{{__('msg.contact')}}</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ End Banner Area =================-->



<!-- ================ contact section start ================= -->
<section class="section-margin">
    <div class="container">



        @if(count($errors)>0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{$error}}</li>
                        @endforeach
                </ul>
            </div>
            @endif
        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">{{__('msg.click')}}</h2>
            </div>
            <div class="col-lg-8 mb-4 mb-lg-0">
                <form class="form-contact contact_form" action="{{route('contact.store')}}" method="post">
                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control w-100" name="message"  cols="30" rows="9" placeholder="{{__('msg.message')}}"></textarea>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control" name="name"  type="text" placeholder="{{__('msg.your_name')}}">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control" name="email"  type="email" placeholder="{{__('msg.email')}}">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" name="subject"  type="text" placeholder="{{__('msg.subject')}} ">
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-lg-3">
                        <button type="submit" class="primary_btn button-contactForm">{{__('msg.send')}}</button>
                    </div>
                </form>


            </div>

            <div class="col-lg-4">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-home"></i></span>
                    <div class="media-body">
                        <h3>{{__('msg.add1')}}</h3>
                        <p>{{__('msg.add2')}}</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                    <div class="media-body">
                        <h3><a href="tel:454545654">09030949922</a></h3>
                        <p>{{__('msg.time_to_answer_phone')}}</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3><a href="mailto:support@colorlib.com">hanavel.ir@gmail.com</a></h3>
                        <p>{{__('msg.time_to_answer_email')}} </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ================ contact section end ================= -->
<!--================Footer Area =================-->
<!--================End Footer Area =================-->
@endsection

resources/views/partials/footer.blade.php
    <footer class="footer_area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="footer_top flex-column">
                        <div class="footer_logo">
                            <a href="{{route('home')}}">
                                <img src="{{asset('img/logo2.png')}}" alt="">
                            </a>
                            <div class="d-lg-block d-none">
                                <nav class="navbar navbar-expand-lg navbar-light justify-content-center">
                                    <div class="collapse navbar-collapse offset">
                                        <ul class="nav navbar-nav menu_nav mx-auto">
                                            <li class="nav-item"><a class="nav-link text-white" href="{{url('/')}}">{{__('msg.home')}}</a></li>
                                            <li class="nav-item"><a class="nav-link text-white" href="{{url('about_me')}}">{{__('msg.about_me')}}</a></li>
                                            <li class="nav-item"><a class="nav-link text-white" href="{{route('frontend.posts')}}">{{__('msg.blog')}}</a></li>
                                            <li class="nav-item"><a class="nav-link text-white" href="{{route('contact.index')}}">{{__('msg.contact')}} </a></li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row footer_bottom justify-content-center">
                <p class="col-lg-8 col-sm-12 footer-text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i>by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </footer>

resources/views/partials/form-errors.blade.php
@if(count($errors)>0)

    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>

@endif

resources/views/partials/navigation.blade.php
<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{{route('home')}}"><img src="{{asset('img/logo.png')}}" alt=""></a>
                <a class="navbar-brand logo_inner_page" href="{{route('home')}}"><img src="{{asset('img/logo2.png')}}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav">
                        <li class="nav-item active"><a class="nav-link" href="{{url('/')}}">{{__('home')}}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{route('about_me',app()->getLocale())}}">{{__('about_me')}} </a></li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">{{__('blog')}}</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{{route('frontend.posts',app()->getLocale())}}">{{__('blog')}}</a></li>
                            </ul>
                        </li>

                        <li class="nav-item"><a class="nav-link" href="{{route('contact.index',app()->getLocale())}}">{{__('contact')}}</a></li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">{{__('language')}}</a>
                            <ul class="dropdown-menu">
{{--                                {{route(\Illuminate\Support\Facades\Route::currentRouteName(),'fa')}}--}}
                                <li class="nav-item"><a class="nav-link" href="locale/fa"><img src="{{asset('img/iran.png')}}" alt="" style=" width: 20px;"  > Persian</a></li>
                                <li class="nav-item"><a class="nav-link" href="locale/en"><img src="{{asset('img/usa.png')}}" alt="" style=" width: 20px;"> English </a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>

resources/views/partials/sidebar.blade.php
<!-- Search Widget -->
<div class="card my-4">
    <h5 class="card-header">جستجو</h5>
    <div class="card-body">

        {!! Form::open((['method' => 'GET', 'action'=> 'Frontend\PostController@searchTitle']))!!}
        <div class="input-group">
            {!! Form::text('title', null, ['class'=>'form-control']) !!}
            <span class="input-group-btn">
                {!! Form::submit('جستجو', ['class'=>'btn btn-secondary']) !!}
            </span>
        </div>
        {!! Form::close() !!}
    </div>
</div>

<!-- Categories Widget -->
<div class="card my-4">
    <h5 class="card-header">دسته بندی ها</h5>
    <div class="card-body">
        <ul class="list-unstyled mb-0">
            @foreach($categories as $category)
                <li class="nav-item">
                    <a class="nav-link" href="#">{{$category->title}}</a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

<!-- Side Widget -->
<div class="card my-4">
    <h5 class="card-header">Side Widget</h5>
    <div class="card-body">
        You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
    </div>
</div>