routes/web.php
<?php

use App\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//blog route
Route::get('/posts', 'Frontend\MainController@posts')->name('frontend.posts');
Route::get('/posts/{slug}', 'Frontend\PostController@show')->name('frontend.posts.show');
Route::post('comments/{postId}', 'Frontend\CommentController@store')->name('frontend.comments.store');
Route::post('comments}', 'Frontend\CommentController@reply')->name('frontend.comments.reply');
Route::get('search', 'Frontend\PostController@searchTitle' )->name('frontend.posts.search');



// personal-site route

Route::get('/', function () {
    $recently = Post::with('user', 'category', 'photo')
        ->where('status', 1)
        ->orderBy('created_at', 'desc')->paginate(3);
    return view('welcome', compact('recently'));
})->name('home');
Route::get('/about_me', 'Frontend\MainController@about_me')->name('about_me');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('contact','Frontend\MailController');


// admin route
Route::group(['before' => 'auth', 'middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('dashboard', 'Admin\AdminDashboardController@index')->name('dashboard');
    Route::resource('users', 'Admin\AdminUserController');
    Route::resource('posts', 'Admin\AdminPostController');
    Route::resource('categories', 'Admin\AdminCategoryController');
    Route::resource('photos', 'Admin\AdminPhotoController');
    Route::get('photos/upload', ['as' => 'photos.upload', 'use' => 'Admin\AdminPhotoController@upload']);
    Route::get('comments', 'Admin\CommentController@index')->name('comments.index');
    Route::post('actions/{id}', 'Admin\CommentController@actions')->name('comments.actions');
    Route::get('comments/{id}', 'Admin\CommentController@edit')->name('comments.edit');
    Route::patch('comments/{id}', 'Admin\CommentController@update')->name('comments.update');
    Route::delete('comments/{id}', 'Admin\CommentController@destroy')->name('comments.destroy');
    Route::delete('delete/media', 'Admin\AdminPhotoController@deleteAll')->name('photo.delete.all');
});
Route::get('locale/{locale}', function ($locale) {
  \Illuminate\Support\Facades\Session::put('locale',$locale);
  return redirect()->back();
});

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/images/';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function photo()
    {
        return $this->belongsTo(Photo::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/Frontend/PostController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Category;
use App\Comment;
use App\Http\Controllers\Controller;
use App\Post;
use Illuminate\Http\Request;
use Symfony\Component\Console\Input\Input;

class PostController extends Controller
{
    public function show($slug)
    {
        $post = Post::with(['user','category','photo',
            'comments'=>function($q){
                $q->where('status', 1)
                    ->where('parent_id', null);
            }, 'comments.replies'=>function($q){
                $q->where('status', 1);
            }])
            ->where('slug', $slug)
            ->where('status', 1)
            ->first();
        $categories = Category::all();
        $recently = Post::with('user', 'category', 'photo')
            ->where('status', 1)
            ->orderBy('created_at', 'desc')->paginate(5);

        return view('frontend.posts.show', compact(['post', 'categories','recently']));
    }
    public function searchTitle()
    {
        $query = Input::get('title');
        $posts = Post::with('user','category','photo')
            ->where('title', 'like', "%".$query."%")
            ->where('status', 1)
            ->orderBy('created_at', 'desc')
            ->paginate(3);
        $categories = Category::all();

        return view('frontend.posts.search', compact(['posts', 'categories', 'query']));
    }
}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.master')
@section('content')
        <h3 class="p-b-2 text-center">ایجاد مطلب جدید</h3>

        <div class="row">
            <div class="col-md-10 offset-md-1">
                @include('partials.form-errors')
             <form action="{{route('posts.store')}}" METHOD="POST" enctype="multipart/form-data">
                 @csrf
                <div class="form-group">
                    {!! Form::label('title', 'عنوان:') !!}
                    {!! Form::text('title', null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('slug', 'نام مستعار:') !!}
                    {!! Form::text('slug', null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('category', 'دسته بندی:') !!}
                    {!! Form::select('category', $categories, null,['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('description', 'توضیحات:') !!}
                    {!! Form::textarea('description', null, ['class'=>'form-control']) !!}

                </div>
                <div class="form-group">
                    {!! Form::label('status', 'وضعیت:') !!}
                    {!! Form::select('status', [1=>'فعال', 0=>'غیرفعال'], 0, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('first_photo', 'تصویر اصلی:') !!}
                    {!! Form::file('first_photo', null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('meta_description', 'متا توضیحات:') !!}
                    {!! Form::textarea('meta_description', null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('meta_keywords', 'متا برچسب ها:') !!}
                    {!! Form::textarea('meta_keywords', null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::submit('ذخیره', ['class'=>'btn btn-success']) !!}
                </div>
             </form>
            </div>

        </div>



@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.master')


@section('content')
    <h3 class="p-b-2 text-center">ویرایش مطلب</h3>

    <div class="row">
        <div class="col-md-3">
            <img src="{{$post->photo ? $post->photo->path : "http://www.placehold.it/400" }}" class="img-fluid">
        </div>
        <div class="col-md-9">
            @include('partials.form-errors')
            {!! Form::model($post, ['method' => 'PATCH', 'action'=> ['Admin\AdminPostController@update', $post->id], 'files'=>true]) !!}
            <div class="form-group">
                {!! Form::label('title', 'عنوان:') !!}
                {!! Form::text('title', $post->title, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('slug', 'نام مستعار:') !!}
                {!! Form::text('slug', $post->slug, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('category', 'دسته بندی:') !!}
                {!! Form::select('category', $categories, $post->category->id,['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description', 'توضیحات:') !!}
                {!! Form::textarea('description', $post->description, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('status', 'وضعیت:') !!}
                {!! Form::select('status', [1=>'فعال', 0=>'غیرفعال'], $post->status, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('first_photo', 'تصویر اصلی:') !!}
                {!! Form::file('first_photo', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_description', 'متا توضیحات:') !!}
                {!! Form::textarea('meta_description', $post->meta_description, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_keywords', 'متا برچسب ها:') !!}
                {!! Form::textarea('meta_keywords', $post->meta_keywords, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('بروزرسانی', ['class'=>'btn btn-success col-md-3']) !!}
            </div>
            {!! Form::close() !!}

            {!! Form::open(['method' => 'DELETE', 'action'=> ['Admin\AdminPostController@destroy', $post->id]]) !!}
            <div class="form-group">
                {!! Form::submit('حذف', ['class'=>'btn btn-danger col-md-3']) !!}
            </div>
            {!! Form::close() !!}
        </div>


    </div>

@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.master')


@section('content')

    @if(Session::has('delete_post'))
        <div class="alert alert-danger">
            <div>{{session('delete_post')}}</div>
        </div>
    @endif
    @if(Session::has('add_post'))
        <div class="alert alert-success">
            <div>{{session('add_post')}}</div>
        </div>
    @endif
    @if(Session::has('update_post'))
        <div class="alert alert-success">
            <div>{{session('update_post')}}</div>
        </div>
    @endif
    <h3 class="p-b-2">لیست مطالب</h3>
    <table class="table table-hover bg-content">
        <thead>
        <tr>
            <th></th>
            <th>عنوان</th>
            <th>کاربر</th>
            <th>توضیحات</th>
            <th>دسته بندی</th>
            <th>وضعیت</th>
            <th>تاریخ ایجاد</th>
        </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
            <tr>
                <td><img src="{{$post->photo ? $post->photo->path : "http://www.placehold.it/400" }}" class="img-fluid" width="80"></td>
                <td><a href="{{route('posts.edit', $post->id)}}">{{$post->title}}</a></td>
                <td>{{$post->user->name}}</td>
                <td>{{Illuminate\Support\Str::limit($post->description, 50,' (...)')}}</td>
                <td>{{$post->category->title}}</td>
                @if($post->status == 0)
                    <td><span class="tag tag-pill tag-danger">غیرفعال</span></td>
                @else
                    <td><span class="tag tag-pill tag-success">فعال</span></td>
                @endif

                <td>{{\Hekmatinasser\Verta\Verta::instance($post->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="col-md-12" style="text-align: center">{{$posts->links()}}</div>
@endsection