routes/web.php
<?php

use App\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//blog route
Route::get('/posts', 'Frontend\MainController@posts')->name('frontend.posts');
Route::get('/posts/{slug}', 'Frontend\PostController@show')->name('frontend.posts.show');
Route::post('comments/{postId}', 'Frontend\CommentController@store')->name('frontend.comments.store');
Route::post('comments}', 'Frontend\CommentController@reply')->name('frontend.comments.reply');
Route::get('search', 'Frontend\PostController@searchTitle' )->name('frontend.posts.search');



// personal-site route

Route::get('/', function () {
    $recently = Post::with('user', 'category', 'photo')
        ->where('status', 1)
        ->orderBy('created_at', 'desc')->paginate(3);
    return view('welcome', compact('recently'));
})->name('home');
Route::get('/about_me', 'Frontend\MainController@about_me')->name('about_me');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('contact','Frontend\MailController');


// admin route
Route::group(['before' => 'auth', 'middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('dashboard', 'Admin\AdminDashboardController@index')->name('dashboard');
    Route::resource('users', 'Admin\AdminUserController');
    Route::resource('posts', 'Admin\AdminPostController');
    Route::resource('categories', 'Admin\AdminCategoryController');
    Route::resource('photos', 'Admin\AdminPhotoController');
    Route::get('photos/upload', ['as' => 'photos.upload', 'use' => 'Admin\AdminPhotoController@upload']);
    Route::get('comments', 'Admin\CommentController@index')->name('comments.index');
    Route::post('actions/{id}', 'Admin\CommentController@actions')->name('comments.actions');
    Route::get('comments/{id}', 'Admin\CommentController@edit')->name('comments.edit');
    Route::patch('comments/{id}', 'Admin\CommentController@update')->name('comments.update');
    Route::delete('comments/{id}', 'Admin\CommentController@destroy')->name('comments.destroy');
    Route::delete('delete/media', 'Admin\AdminPhotoController@deleteAll')->name('photo.delete.all');
});
Route::get('locale/{locale}', function ($locale) {
  \Illuminate\Support\Facades\Session::put('locale',$locale);
  return redirect()->back();
});

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/images/';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

resources/views/admin/photos/create.blade.php
@extends('admin.layouts.master')

@section('styles')
    <link rel="stylesheet" href="{{asset('css/dropzone.css')}}">
@endsection

@section('content')
    <h3 class="p-b-2 text-center">آپلود فایل</h3>

    <div class="row">
        <div class="col-md-10 offset-md-1">
            @include('partials.form-errors')
            <form action="{{route('photos.store')}}" METHOD="POST" enctype="multipart/form-data" class="dropzone">
                @csrf
            </form>

        </div>

    </div>

@endsection

@section('scripts')
    <script src="{{asset('js/dropzone.js')}}"></script>
@endsection

resources/views/admin/photos/list.blade.php
@extends('admin.layouts.master')

@section('scripts')
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script>
        $(document).ready(function(){
            $('#options').click(function(){
                if(this.checked){
                    $('.checkBox').each(function(){
                        this.checked = true;
                    })
                }else{
                    $('.checkBox').each(function(){
                        this.checked = false;
                    })
                }

            })
        })
    </script>
@endsection

@section('content')
    @if(Session::has('delete_photo'))
        <div class="alert alert-danger">
            <div>{{session('delete_photo')}}</div>
        </div>
    @endif
    @if(Session::has('delete_photos'))
        <div class="alert alert-danger">
            <div>{{session('delete_photos')}}</div>
        </div>
    @endif
    <h3 class="p-b-2">لیست فایل ها</h3>

    <form action="/admin/delete/media" method="post" class="form-inline">
        {{csrf_field()}}
        {{method_field('delete')}}
        <div class="form-group">
            <select name="checkBoxArray" id="" class="form-control">
                <option value="delete">حذف دسته جمعی</option>
            </select>
            <input type="submit" name="submit" class="btn btn-primary" value="اعمال">
        </div>


        <table class="table table-hover bg-content" style="margin-top: 10px;">
            <thead>
            <tr>
                <th><input type="checkbox" id="options"></th>
                <th>شناسه</th>
                <th>تصویر</th>
                <th>کاربر</th>
                <th>تاریخ ایجاد</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($photos as $photo)
                <tr>
                    <td><input class="checkBox" type="checkbox" name="checkBoxArray[]" value="{{$photo->id}}"></td>
                    <td>{{$photo->id}}</td>
                    <td><img src="{{$photo->path }}" class="img-fluid" width="80"></td>
                    <td>{{$photo->user->name}}</td>
                    <td>{{\Hekmatinasser\Verta\Verta::instance($photo->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</td>
                    <td>
                        {!! Form::open(['method' => 'DELETE', 'route'=>['photos.destroy', $photo->id]]) !!}
                        <div class="form-group">
                            {!! Form::submit('حذف', ['class'=>'btn btn-danger']) !!}
                        </div>
                        {!! Form::close() !!}

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </form>
    <div class="col-md-12" style="text-align: center">{{$photos->links()}}</div>
@endsection