routes/web.php
<?php

use App\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//blog route
Route::get('/posts', 'Frontend\MainController@posts')->name('frontend.posts');
Route::get('/posts/{slug}', 'Frontend\PostController@show')->name('frontend.posts.show');
Route::post('comments/{postId}', 'Frontend\CommentController@store')->name('frontend.comments.store');
Route::post('comments}', 'Frontend\CommentController@reply')->name('frontend.comments.reply');
Route::get('search', 'Frontend\PostController@searchTitle' )->name('frontend.posts.search');



// personal-site route

Route::get('/', function () {
    $recently = Post::with('user', 'category', 'photo')
        ->where('status', 1)
        ->orderBy('created_at', 'desc')->paginate(3);
    return view('welcome', compact('recently'));
})->name('home');
Route::get('/about_me', 'Frontend\MainController@about_me')->name('about_me');
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('contact','Frontend\MailController');


// admin route
Route::group(['before' => 'auth', 'middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('dashboard', 'Admin\AdminDashboardController@index')->name('dashboard');
    Route::resource('users', 'Admin\AdminUserController');
    Route::resource('posts', 'Admin\AdminPostController');
    Route::resource('categories', 'Admin\AdminCategoryController');
    Route::resource('photos', 'Admin\AdminPhotoController');
    Route::get('photos/upload', ['as' => 'photos.upload', 'use' => 'Admin\AdminPhotoController@upload']);
    Route::get('comments', 'Admin\CommentController@index')->name('comments.index');
    Route::post('actions/{id}', 'Admin\CommentController@actions')->name('comments.actions');
    Route::get('comments/{id}', 'Admin\CommentController@edit')->name('comments.edit');
    Route::patch('comments/{id}', 'Admin\CommentController@update')->name('comments.update');
    Route::delete('comments/{id}', 'Admin\CommentController@destroy')->name('comments.destroy');
    Route::delete('delete/media', 'Admin\AdminPhotoController@deleteAll')->name('photo.delete.all');
});
Route::get('locale/{locale}', function ($locale) {
  \Illuminate\Support\Facades\Session::put('locale',$locale);
  return redirect()->back();
});

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/images/';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function photo()
    {
        return $this->belongsTo(Photo::class);
    }
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    public function isAdmin()
    {
        foreach ($this->roles as $role){
            if($role->name == 'admin' && $this->status == 1){
                return true;
            }
        }
        return false;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <form action="{{route('users.store')}}" METHOD="POST" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col-md-6 offset-md-3">
                @include('partials.form-errors')
                <div class="form-group">
                    <div class="small-12 medium-2 large-2 columns">
                        <div class="circle">
                            <!-- User Profile Image -->
                            <img class="profile-pic"
                                 src="http://cdn.cutestpaw.com/wp-content/uploads/2012/07/l-Wittle-puppy-yawning.jpg">

                            <!-- Default Image -->
                            <i class="fa fa-user fa-5x"></i>
                        </div>
                        <div class="p-image">
                            <i class="fa fa-camera upload-button"></i>
                            <input class="file-upload" name="avatar" type="file" accept="image/*" ref="file" "/>

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="validationCustom01">نام کاربری:</label>
                    <input type="text" class="form-control" name="user_name" placeholder="برای مثال : alirostami"
                    >
                </div>
                <div class="form-group">
                    <label for="validationCustom01">نام و نام خانوادگی :</label>
                    <input type="text" class="form-control" name="name" placeholder="برای مثال : علی رستمی"
                    >
                </div>
                <div class="form-group">
                    <label for="validationCustom01">ایمیل :</label>
                    <input type="email" class="form-control" name="email" placeholder="برای مثال : alirostami@gmail.com"
                    >
                </div>
                <div class="form-group">
                    {!! Form::label('status', 'وضعیت کاربر را وارد کنید:') !!}
                    {!! Form::select('status', [1=>'فعال', 0=>'غیرفعال'], 0, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('roles', 'نقش را وارد کنید :') !!}
                    {!! Form::select('roles[]', $roles, null,['multiple'=>'multiple', 'class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    <label>رمز عبور :</label>
                    <input type="password" class="form-control" name="password">
                    <small id="emailHelp" class="form-text text-muted">رمز عبور باید بیشتر از 6 کاراکتر باشد</small>
                </div>
                <div class="form-group">
                    <label>تایید رمز عبور :</label>
                    <input type="password" class="form-control" name="confirmed">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">ثبت کاربر</button>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.master')


@section('content')
    <h3 class="p-b-2 text-center"><a href="{{$user->name}}"></a> ویرایش کاربر  </h3>

    <div class="row">
        <div class="col-md-3">
            <img src="{{$user->photo ? $user->photo->path : "http://www.placehold.it/400" }}" class="img-fluid">
        </div>
        <div class="col-md-9">
            @include('partials.form-errors')
            {!! Form::model($user, ['method' => 'PATCH', 'route'=> ['users.update', $user->id], 'files' => true]) !!}
            <div class="form-group">
                {!! Form::label('user_name', 'نام کاربری:') !!}
                {!! Form::text('user_name', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('name', 'نام و نام خانوادگی:') !!}
                {!! Form::text('name', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('email', 'ایمیل:') !!}
                {!! Form::text('email', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('roles', 'نقش:') !!}
                {!! Form::select('roles[]', $roles, null,['multiple'=>'multiple', 'class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('status', 'وضعیت:') !!}
                {!! Form::select('status', [1=>'فعال', 0=>'غیرفعال'], null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('avatar', 'تصویر پروفایل:') !!}
                {!! Form::file('avatar', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('password', 'رمز عبور:') !!}
                {!! Form::password('password', ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('confirm_password', ' تکرار رمز عبور:') !!}
                {!! Form::password('confirm_password', ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('بروزرسانی', ['class'=>'btn btn-success col-md-3']) !!}
            </div>
            {!! Form::close() !!}

            {!! Form::open(['method' => 'DELETE', 'route'=> ['users.destroy', $user->id]]) !!}
            <div class="form-group">
                {!! Form::submit('حذف', ['class'=>'btn btn-danger col-md-3']) !!}
            </div>
            {!! Form::close() !!}
        </div>


    </div>

@endsection

resources/views/admin/user/list.blade.php
@extends('admin.layouts.master')


@section('content')
<h3 class="p-b-2">لیست کاربران</h3>
<table class="table table-hover bg-content">
    <thead>
    <tr>
        <th></th>
        <th>نام</th>
        <th>ایمیل</th>
        <th>نقش</th>
        <th>وضعیت</th>
        <th>تاریخ ایجاد</th>
    </tr>
    </thead>
    <tbody>
    @foreach($users as $user)
        <tr>
            <td><img src="{{$user->photo ? $user->photo->path : "http://www.placehold.it/400" }}" class="img-fluid" width="80"></td>
            <td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
            <td>{{$user->email}}</td>
            <td>
                <ul style="list-style: none;">
                    @foreach($user->roles as $role)
                        <li>{{$role->name}}</li>
                    @endforeach
                </ul>
            </td>
            @if($user->status == 0)
                <td><span class="tag tag-pill tag-danger">غیرفعال</span></td>
            @else
                <td><span class="tag tag-pill tag-success">فعال</span></td>
            @endif

            <td>{{\Hekmatinasser\Verta\Verta::instance($user->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="col-md-12" style="text-align: center">{{$users->links()}}</div>
@endsection